package fr.diginamic.testexceptions;

public class TestRuntimeException {

	public static void main(String[] args) {
		
		
		System.out.println(Operation.diviserRuntime(4, 8));
		
		System.out.println(Operation.diviserRuntime(4, 0));
		

	}

}
